destination: ./content
lsi:         false
port: 4000
highlighter:    pygments
markdown:    Kramdown
permalink:   date
exclude:      [readme.md]
wicket:
  version:    6.20.0
  version_70: 7.0.0-M6
  version_60: 6.20.0
  version_15: 1.5.13
  version_14: 1.4.23
  released:   2015-06-14
  versions:   [6.20.0, 1.5.13, 1.4.23, 7.0.0-M6, 1.5-SNAPSHOT, 6.21.0-SNAPSHOT, 7.0.0-SNAPSHOT]
